language: node_js
sudo: false
dist: trusty
node_js:
- lts/*
script:
- gulp lint
- gulp test
deploy:
  skip_cleanup: true
  provider: script
  script: npm publish
  on:
    all_branches: true
    condition: "$TRAVIS_TAG =~ v[0-9]+\\.[0-9]+\\.[0-9]+"
    repo: BenjaminVanRyseghem/switchless-redux-actions
